### ISSUE TITLE
Allow server side rendering

### ISSUE THREAD

**Issue by bebraw** [mrded/is-url-external#2]
The `window` dependency is problematic in Node. It might be a good idea to perform a check against it or document the limitation.

**Comment by diegolamanno** [comment]
I just had the same issue using this with [Gatsby](https://www.gatsbyjs.org/). Would be nice to get it fix.

**Comment by jonny-harte** [comment]
I'm having the same issue with Gatsby. Any fix/progress on this?

**Comment by jonny-harte** [comment]
For anyone else having issue with Gatsby. I combined it with use-ssr hook to check its in the browser.

https://github.com/alex-cory/use-ssr

**Comment by nextlevelshit** [comment]
I've just found this: https://github.com/muhajirdev/is-internal-link

**Comment by mrded** [comment]
Sorry, it took me some time to go over my notification :) 

Please have a look at this https://github.com/mrded/is-url-external/pull/4

This will also add nodejs support.

**Comment by mrded** [comment]
Solved. Sorry again for the wait.
